language: rust
dist: xenial
sudo: true
os: linux

# source: https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo install cargo-tarpaulin -f
    fi
  - rm -rf /home/travis/.cargo/registry

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update

script:
  - cargo clean
  - cargo build --verbose --all
  - cargo test --verbose --all
  
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
