[package]
name = "bcl2fastr"
version = "0.1.0"
authors = ["phoenixAja <phoenix@phoenixlogan.net>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "*"
byteorder = "1.3.2"
glob = "0.3.0"


[build-dependencies]
cc = "1.0"
