[package]
name = "bcl2fastr"
version = "0.1.0"
authors = ["phoenixAja <phoenix@phoenixlogan.net>"]
edition = "2018"

[dependencies]
serde = { "version" = "1.0", "features" = ["derive"] }
serde-xml-rs = "0.3.1"
byteorder = "1.3.2"
glob = "0.3.0"
flate2 = "1.0"

[build-dependencies]
cc = "1.0"
