[package]
name = "bcl2fastr"
version = "0.1.0"
authors = [
  "phoenixAja <phoenix@phoenixlogan.net>", 
  "James Webber <james.webber@czbiohub.org>",
]
edition = "2018"

[dependencies]
serde = { "version" = "1.0", "features" = ["derive"] }
serde-xml-rs = "0.3.1"
byteorder = "1.3.2"
flate2 = "1.0"
ndarray = "0.13.0"
clap = "2.33"
bitvec = "0.15"

[build-dependencies]
cc = "1.0"
